robot_id: 'robot_1'

cam_params:
  focal_length: 2.32 # dist = 1/f
  dist_cam_robot_center: 0.098 #meters
  aruco_square_size: 0.038 #meters

# Define here the ids and respective positions of the aruco codes

aruco_params:
  157: # testing
    t_x: 0.123
    t_y: 0.456
    yaw: 0.0
  11:
    t_x: 4.352
    t_y: 6.368
    yaw: 0.0
  618:
    t_x: 4.402
    t_y: 7.358
    yaw: 0.0
  645:
    t_x: 4.36
    t_y: 5.463
    yaw: 0.0
  614:
    t_x: 4.38
    t_y: 4.56
    yaw: 0.0

